const stubData = [
  {
    id: 0,
    name: 'Vue3 Typescript Bookmarks: github repository',
    url: 'https://github.com/sedovdmitry/vue3-ts-bookmarks',
    createdAt: Date.now(),
    updatedAt: null,
    deletedAt: null,
  },
  {
    id: 1,
    name: 'facebook',
    url: 'https://www.facebook.com/',
    createdAt: Date.now(),
    updatedAt: null,
    deletedAt: null,
  },
  {
    id: 2,
    name: 'Функциональное программирование на JS',
    url: 'https://habr.com/ru/post/154105/',
    createdAt: Date.now(),
    updatedAt: null,
    deletedAt: null,
  },
  {
    id: 3,
    name: 'Apple',
    url: 'https://apple.com/',
    createdAt: Date.now(),
    updatedAt: null,
    deletedAt: null,
  },
  {
    id: 4,
    name: 'Google',
    url: 'https://google.com/',
    createdAt: Date.now(),
    updatedAt: null,
    deletedAt: null,
  },
  {
    id: 5,
    name: 'Oracle',
    url: 'https://oracle.com/',
    createdAt: Date.now(),
    updatedAt: null,
    deletedAt: null,
  },
  {
    id: 6,
    name: 'Node',
    url: 'https://nodejs.org/en/',
    createdAt: Date.now(),
    updatedAt: null,
    deletedAt: null,
  },
  {
    id: 7,
    name: 'React',
    url: 'https://ru.reactjs.org/',
    createdAt: Date.now(),
    updatedAt: null,
    deletedAt: null,
  },
  {
    id: 8,
    name: 'Nest',
    url: 'https://nestjs.com/',
    createdAt: Date.now(),
    updatedAt: null,
    deletedAt: null,
  },
  {
    id: 9,
    name: 'Typescript',
    url: 'https://www.typescriptlang.org/',
    createdAt: Date.now(),
    updatedAt: null,
    deletedAt: null,
  },
  {
    id: 10,
    name: 'Webpack',
    url: 'https://webpack.js.org/',
    createdAt: Date.now(),
    updatedAt: null,
    deletedAt: null,
  },
];

export default stubData;
