// Generated by https://quicktype.io

export interface Source {
  id: string;
  name: string;
}

export interface Article {
  source: Source;
  author: string;
  title: string;
  description: string;
  url: string;
  urlToImage: string;
  publishedAt: string;
  content: string;
}

export interface NewsAPITypes {
    status?: string;
    totalArticles?: number;
    articles?: Article[];
}
